### ISSUE TITLE
max.py: blockdim and grimdim swapped?

### ISSUE THREAD

**Issue by hanbinlu** [ContinuumIO/numbapro-examples#12]
Is it possible in the function call:
max_kernel[griddim, blockdim](d_a, d_b)
of the max.py example, the blockdim and griddim are swapped?

**Comment by sklam** [comment]
I don't think they are swapped.

```python
griddim = blkct, 1
blockdim = a.size//blkct, 1
max_kernel[griddim, blockdim](d_a, d_b)
```

A grid contains threadblocks, which contain threads.  Therefore, `griddim` is assigned to the number of block; and, `blockdim` is assigned to number of item divided by number of block.  Each thread is assumed to work on one item.

**Comment by sf-nevermore** [comment]
I thought blkct was the thread number of each block instead of number of blocks. The blockdim has hardware limitation, in your example you set as 256. Would it be more straightforward to set blkct as 256 and griddim as  a.size//blkct if n is not a small size like 20 in the example, eg. 10000. By the way, if there is remainder of n/blkct, [griddim, blockdim] will not hold every items.
I did it like that:
blkct = 256 
blockdim = blkct, 1
griddim = a.size//blkct+1, 1
max_kernel[griddim, blockdim](d_a, d_b)

**Comment by sklam** [comment]
You're right.  The example is overly-simplified for the handling of threadcount and of the remainder.
